# Generated by Django 3.0.14 on 2022-05-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websiteName', models.CharField(max_length=1000)),
                ('websiteLink', models.URLField(max_length=8000)),
                ('createdAt', models.DateField()),
                ('lastScrappedAt', models.TimeField()),
            ],
        ),
    ]
