# Generated by Django 3.0.14 on 2022-05-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsscrap', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleDesc',
            field=models.TextField(max_length=50000),
        ),
    ]
