# Generated by Django 3.0.14 on 2022-05-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsscrap', '0003_auto_20220529_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='websiteID',
        ),
    ]
