# Generated by Django 3.0.14 on 2022-05-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsscrap', '0005_auto_20220529_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleDOM',
            field=models.CharField(max_length=10000),
        ),
    ]
