# Generated by Django 3.0.14 on 2022-05-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsscrap', '0006_auto_20220529_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleDOM',
            field=models.TextField(max_length=10000),
        ),
    ]
