# Generated by Django 3.0.14 on 2022-05-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsscrap', '0007_auto_20220529_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='website_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsscrap.Website'),
        ),
    ]
